version: "3.7"
services:
  web:
    image: node:14-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - "4040:4040"
    working_dir: /scaling-octo-disco
    volumes:
      - ./:/scaling-octo-disco